# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fib_series', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibonacciseries',
            name='num',
            field=models.IntegerField(unique=True),
        ),
    ]
